version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: ./bin/rails server -b 0.0.0.0

  sidekiq:
    build: .
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: bundle exec sidekiq

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data: